name: estrellas_dashboard
description: "Estrellas Dashboard"
publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  json_serializable: ^6.8.0
  package_info_plus: ^8.0.2
  rxdart: ^0.28.0
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  lottie: ^3.1.2
  adaptive_dialog: ^2.2.1
  macos_window_utils: ^1.5.0
  universal_platform: ^1.1.0
  cupertino_modal_sheet: ^1.1.0
  flutter_svg: ^2.0.10
  get: ^4.6.6
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  reactive_forms: ^17.0.1
  shimmer: ^3.0.0
  json_editor: ^0.0.8
  http: ^1.2.2
  intl: ^0.19.0
  video_compress: ^3.1.3
  image_picker: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
